baseurl             = "https://pingqingsheng.github.io/"
languageCode        = "en-us"
title               = "ZSZ"
theme               = "introduction"
enforce_ssl         = "your-url.com"
builddrafts         = false
canonifyurls        = true
contentdir          = "content"
layoutdir           = "layouts"
publishdir          = "public"
disqusshortname     = "test" # Enable Disqus for comments
#googleAnalytics    = "UA-97431971-1"

[permalinks]
fixed = ":title/"
blog  = "blog/:slug/"

[params]
author        = "ZSZ" # Full name shows on blog post pages
firstname     = "ZSZ" # First name shows in introduction on main page
tagline       = "The Space is Under Construction" # Appears after the introduction
introheight   = "large" # Input either 'medium' or 'large' or 'fullheight'
avatar        = "img/profile.png" # Path to image in static folder eg. img/avatar.png 
email         = "imzszhahahaha@email.com" # Shows in contact section, or leave blank to omit
dateform      = "April 14, 2017"
dateformfull  = "Fri. April 14 2017 21:40:05 EST"
cachebuster   =  true # Add the current unix timestamp in query string for cache busting css assets
description   = "This Site is Under Construction"
faviconfile   = "img/fav.ico"
highlightjs   =  true # Syntax highlighting
lang          = "en"
footertext    = "" # Text to show in footer (overrides default text)

# Social icons appear in introduction and contact section. Input your username only, eg "you" as it appears in "twitter.com/you"
linkedin      = "you"
twitter       = ""
github        = "pingqingsheng"
codepen       = "you"
pinterest     = ""
facebook      = ""
googleplus    = "Qing Sheng Ping"

showblog        = true # Show Blog section on home page
showallposts    = false # Set 'true' to list all posts on home page, or set 'false' to link to separate blog list page
showlatest      = true # Show latest blog post summary
sharebuttons    = true # On post pages, show share this social buttons

showprojects    = true # Show Projects section on home page

# This is your projects section. Three images of the same dimensions will look the nicest. If images are omitted, text links will be shown.
project1link    = "#"
project1img     = "img/project1.jpg"
project1title   = "Project 1"

project2link    = "#"
project2img     = "img/project2.jpg"
project2title   = "Project 2"

project3link    = "#"
project3img     = "img/project3.jpg"
project3title   = "Project 3"
